version: '2.1'
services:
    homeassistant:
        image: lscr.io/linuxserver/homeassistant
        container_name: homeassistant
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
        volumes:
            - /run/dbus:/run/dbus:ro
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
            - /home/pi/docker/homeAssistant/data:/config
        restart: unless-stopped
        devices: 
            - /dev/vcio:/dev/vcio
