version: '2.1'
services:
    homeassistant:
        image: lscr.io/linuxserver/homeassistant
        container_name: homeassistant
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
        volumes:
            - /run/dbus:/run/dbus:ro
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
            - /home/pi/docker/homeAssistant/data:/config
        restart: unless-stopped
        devices: 
            - /dev/vcio:/dev/vcio
        depends_on:
            - tailscale
    tailscale:
        image: tailscale/tailscale:latest
        hostname: rpi
        environment: 
            - TS_AUTHKEY=${TS_OAUTH_KEY}
            - TS_EXTRA_ARGS=--advertise-tags=tag:dev
            - TS_STATE_DIR=/var/lib/tailscale
        volumes:
            - ${PWD}/tailscale/state:/var/lib/tailscale
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
            - sys_module
        restart: unless-stopped